image: ruby:2.3

test:
  stage: test
  script:
  - gem install jekyll github-pages
  - jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - gh-pages

pages:
  stage: deploy
  script:
  - gem install jekyll github-pages
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - gh-pages